import { AgentStep } from "../types";

export const defaultSignatureTrace: AgentStep[] = [
  {
    id: "step_1",
    type: "agent",
    label: "Risk Agent initialized checkout analysis",
    detail: "Event trigger: Checkout session initiated for customer cust_8921 with cart value ₹7,850.",
    status: "complete",
    timestamp: "14:18:22.102",
    durationMs: 42,
  },
  {
    id: "step_2",
    type: "tool",
    label: 'get_customer_history(customer_id="cust_8921")',
    detail: "Fetched 14 lifetime orders. Calculated return rate 64.3% (9 returns) and 1 past wardrobing flag.",
    status: "complete",
    timestamp: "14:18:22.148",
    output: '{"return_rate": 0.643, "total_orders": 14, "returns_count": 9, "last_return_days_ago": 12}',
    durationMs: 85,
  },
  {
    id: "step_3",
    type: "tool",
    label: 'analyze_cart(cart_id="cart_4102")',
    detail: "Parsed 3 items. Detected duplicate SKU-772 with multiple sizes (M and L) — size bracketing flag.",
    status: "complete",
    timestamp: "14:18:22.235",
    output: '{"has_size_bracketing": true, "bracket_skus": ["SKU-772"], "cart_value": 7850}',
    durationMs: 62,
  },
  {
    id: "step_4",
    type: "tool",
    label: 'get_product_stats(sku_list=["SKU-772-L", "SKU-773-M", "SKU-409"])',
    detail: "Category 'Ethnic Occasionwear' has 38.2% historical return rate. Requires dry-clean restock protocol.",
    status: "complete",
    timestamp: "14:18:22.301",
    output: '{"category_return_rate": 0.382, "restock_cost": 450, "fragility_index": "high"}',
    durationMs: 74,
  },
  {
    id: "step_5",
    type: "ml",
    label: "XGBoost v2.4 Score: 81/100 (High Risk)",
    detail: "Model evaluated 42 feature weights. Primary risk drivers: size bracketing (+0.34) and customer return rate (+0.28).",
    status: "complete",
    timestamp: "14:18:22.380",
    output: '{"raw_probability": 0.814, "risk_level": "high", "top_feature": "size_bracket_count"}',
    durationMs: 38,
  },
  {
    id: "step_6",
    type: "routing",
    label: "Confidence Router: 91% Confidence → Route Direct to Policy Agent",
    detail: "Confidence score 91% exceeds autonomous policy threshold (85%). No secondary human review required.",
    status: "complete",
    timestamp: "14:18:22.420",
    output: '{"routing_branch": "DIRECT_POLICY_AGENT", "requires_manual_audit": false}',
    durationMs: 15,
  },
  {
    id: "step_7",
    type: "agent",
    label: "Policy Agent evaluated margin rules & friction tolerance",
    detail: "Evaluated 4 candidate policies against merchant rule PR-402 (Size Bracketing Mitigation).",
    status: "complete",
    timestamp: "14:18:22.440",
    output: '{"evaluated_policies": 4, "selected_rule": "PR-402_EXCHANGE_FIRST"}',
    durationMs: 50,
  },
  {
    id: "step_8",
    type: "policy",
    label: "Final Policy Assigned: EXCHANGE_FIRST",
    detail: "Defensive policy active: Seamless size swap enabled at delivery; cash refund converted to instant exchange credit.",
    status: "complete",
    timestamp: "14:18:22.495",
    output: '{"policy": "EXCHANGE_FIRST", "protected_margin_inr": 3450}',
    durationMs: 12,
  },
];

export const mockAgentTraces: Record<string, AgentStep[]> = {
  "ORD-9421": defaultSignatureTrace,
  "ORD-9419": [
    {
      id: "step_1",
      type: "agent",
      label: "Risk Agent initialized checkout analysis",
      detail: "Trigger: High-value cart checkout (₹12,400) for customer cust_9012.",
      status: "complete",
      timestamp: "13:22:04.010",
      durationMs: 35,
    },
    {
      id: "step_2",
      type: "tool",
      label: 'get_customer_history(customer_id="cust_9012")',
      detail: "Extracted 17 historical transactions with 15 returned (88.2% return rate) and 3 disputed claims.",
      status: "complete",
      timestamp: "13:22:04.050",
      durationMs: 80,
    },
    {
      id: "step_3",
      type: "tool",
      label: 'analyze_cart(cart_id="cart_4091")',
      detail: "Cart contains Designer Silk Bridal Lehenga (SKU-990). Single high-ticket seasonal piece.",
      status: "complete",
      timestamp: "13:22:04.135",
      durationMs: 45,
    },
    {
      id: "step_4",
      type: "ml",
      label: "XGBoost v2.4 Score: 92/100 (Severe Serial Risk)",
      detail: "Severe return propensity detected based on return frequency and product category.",
      status: "complete",
      timestamp: "13:22:04.185",
      durationMs: 32,
    },
    {
      id: "step_5",
      type: "routing",
      label: "Confidence Router: 94% Confidence → High-Severity Mitigation",
      status: "complete",
      timestamp: "13:22:04.220",
      durationMs: 12,
    },
    {
      id: "step_6",
      type: "policy",
      label: "Final Policy Assigned: RESTOCKING_FEE",
      detail: "Enforced 15% restocking fee on cash refund option; 100% store credit offered with free returns.",
      status: "complete",
      timestamp: "13:22:04.250",
      durationMs: 20,
    },
  ],
  "ORD-9420": [
    {
      id: "step_1",
      type: "agent",
      label: "Risk Agent initialized checkout analysis",
      detail: "Trigger: Standard cart checkout (₹2,499) for customer cust_4310.",
      status: "complete",
      timestamp: "13:54:10.012",
      durationMs: 28,
    },
    {
      id: "step_2",
      type: "tool",
      label: 'get_customer_history(customer_id="cust_4310")',
      detail: "Customer return rate 12.5% (1 of 8 orders). 0 sizing exchange requests.",
      status: "complete",
      timestamp: "13:54:10.045",
      durationMs: 65,
    },
    {
      id: "step_3",
      type: "ml",
      label: "XGBoost v2.4 Score: 18/100 (Low Risk)",
      detail: "All behavioral indicators within healthy merchant baseline.",
      status: "complete",
      timestamp: "13:54:10.115",
      durationMs: 30,
    },
    {
      id: "step_4",
      type: "routing",
      label: "Confidence Router: 96% Confidence → Fast Track Standard Policy",
      status: "complete",
      timestamp: "13:54:10.150",
      durationMs: 10,
    },
    {
      id: "step_5",
      type: "policy",
      label: "Final Policy Assigned: STANDARD_RETURN",
      detail: "Standard 14-day return window applied with zero checkout disruption.",
      status: "complete",
      timestamp: "13:54:10.170",
      durationMs: 14,
    },
  ],
};
