import { Customer } from "../types";

export const mockCustomers: Customer[] = [
  {
    id: "cust_8921",
    name: "Priya Sharma",
    email: "priya.sharma@example.in",
    avatarInitials: "PS",
    returnRate: 0.64,
    previousReturns: 9,
    totalOrders: 14,
    accountAgeDays: 142,
    lifetimeValue: 48500,
    riskTag: "Wardrobing Suspect",
  },
  {
    id: "cust_4310",
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    avatarInitials: "RV",
    returnRate: 0.12,
    previousReturns: 1,
    totalOrders: 8,
    accountAgeDays: 310,
    lifetimeValue: 24200,
  },
  {
    id: "cust_9012",
    name: "Ananya Iyer",
    email: "ananya.iyer@example.org",
    avatarInitials: "AI",
    returnRate: 0.88,
    previousReturns: 15,
    totalOrders: 17,
    accountAgeDays: 68,
    lifetimeValue: 82000,
    riskTag: "Serial Returner",
  },
  {
    id: "cust_1124",
    name: "Vikram Malhotra",
    email: "vikram.m@example.net",
    avatarInitials: "VM",
    returnRate: 0.05,
    previousReturns: 1,
    totalOrders: 22,
    accountAgeDays: 520,
    lifetimeValue: 115000,
  },
  {
    id: "cust_5543",
    name: "Sneha Patel",
    email: "sneha.p@example.com",
    avatarInitials: "SP",
    returnRate: 0.45,
    previousReturns: 5,
    totalOrders: 11,
    accountAgeDays: 95,
    lifetimeValue: 34900,
    riskTag: "Sizing Bracket Patterns",
  },
  {
    id: "cust_7832",
    name: "Aditya Roy",
    email: "aditya.roy@example.in",
    avatarInitials: "AR",
    returnRate: 0.18,
    previousReturns: 2,
    totalOrders: 11,
    accountAgeDays: 240,
    lifetimeValue: 39000,
  },
  {
    id: "cust_6621",
    name: "Meera Nambiar",
    email: "meera.nambiar@example.co",
    avatarInitials: "MN",
    returnRate: 0.72,
    previousReturns: 13,
    totalOrders: 18,
    accountAgeDays: 180,
    lifetimeValue: 71000,
    riskTag: "High Value Returner",
  },
  {
    id: "cust_3390",
    name: "Karan Johar",
    email: "karan.j@example.com",
    avatarInitials: "KJ",
    returnRate: 0.08,
    previousReturns: 1,
    totalOrders: 12,
    accountAgeDays: 410,
    lifetimeValue: 62400,
  },
  {
    id: "cust_8219",
    name: "Divya Sengupta",
    email: "divya.s@example.org",
    avatarInitials: "DS",
    returnRate: 0.52,
    previousReturns: 7,
    totalOrders: 13,
    accountAgeDays: 115,
    lifetimeValue: 46200,
  },
  {
    id: "cust_1945",
    name: "Rohan Kapoor",
    email: "rohan.k@example.net",
    avatarInitials: "RK",
    returnRate: 0.15,
    previousReturns: 3,
    totalOrders: 20,
    accountAgeDays: 490,
    lifetimeValue: 98000,
  },
  {
    id: "cust_4820",
    name: "Tanya Chawla",
    email: "tanya.chawla@example.in",
    avatarInitials: "TC",
    returnRate: 0.81,
    previousReturns: 11,
    totalOrders: 13,
    accountAgeDays: 82,
    lifetimeValue: 56700,
    riskTag: "Wardrobing Suspect",
  },
  {
    id: "cust_7104",
    name: "Manish Reddy",
    email: "manish.reddy@example.com",
    avatarInitials: "MR",
    returnRate: 0.04,
    previousReturns: 0,
    totalOrders: 9,
    accountAgeDays: 290,
    lifetimeValue: 28400,
  }
];
