import { Order } from "../types";
import { mockCustomers } from "./customers";

export const mockOrders: Order[] = [
  {
    id: "ORD-9421",
    customer: mockCustomers[0], // Priya Sharma
    cartValue: 7850,
    currency: "₹",
    riskScore: 81,
    confidence: 91,
    policy: "EXCHANGE_FIRST",
    status: "flagged",
    createdAt: "2026-08-26 14:18:22",
    itemsCount: 3,
    riskLevel: "high",
    items: [
      {
        id: "item_1",
        name: "Embroidered Georgette Anarkali Gown",
        sku: "SKU-772-L",
        category: "Ethnic Occasionwear",
        size: "L",
        price: 3450,
        quantity: 1,
        historicalCategoryReturnRate: 0.38,
      },
      {
        id: "item_2",
        name: "Embroidered Georgette Anarkali Gown",
        sku: "SKU-773-M",
        category: "Ethnic Occasionwear",
        size: "M",
        price: 3450,
        quantity: 1,
        historicalCategoryReturnRate: 0.38,
      },
      {
        id: "item_3",
        name: "Zari Border Silk Dupatta",
        sku: "SKU-409",
        category: "Accessories",
        price: 950,
        quantity: 1,
        historicalCategoryReturnRate: 0.14,
      },
    ],
  },
  {
    id: "ORD-9420",
    customer: mockCustomers[1], // Rahul Verma
    cartValue: 2499,
    currency: "₹",
    riskScore: 18,
    confidence: 96,
    policy: "STANDARD_RETURN",
    status: "processed",
    createdAt: "2026-08-26 13:54:10",
    itemsCount: 2,
    riskLevel: "low",
    items: [
      {
        id: "item_4",
        name: "Slim Fit Cotton Oxford Shirt",
        sku: "SKU-201-40",
        category: "Menswear Basics",
        size: "40",
        price: 1499,
        quantity: 1,
        historicalCategoryReturnRate: 0.12,
      },
      {
        id: "item_5",
        name: "Classic Stretch Chino Trousers",
        sku: "SKU-312-32",
        category: "Menswear Basics",
        size: "32",
        price: 1000,
        quantity: 1,
        historicalCategoryReturnRate: 0.15,
      },
    ],
  },
  {
    id: "ORD-9419",
    customer: mockCustomers[2], // Ananya Iyer
    cartValue: 12400,
    currency: "₹",
    riskScore: 92,
    confidence: 94,
    policy: "RESTOCKING_FEE",
    status: "flagged",
    createdAt: "2026-08-26 13:22:04",
    itemsCount: 4,
    riskLevel: "high",
    items: [
      {
        id: "item_6",
        name: "Raw Silk Designer Lehenga Set",
        sku: "SKU-990",
        category: "Bridal & Occasion",
        price: 8900,
        quantity: 1,
        historicalCategoryReturnRate: 0.52,
      },
      {
        id: "item_7",
        name: "Statement Kundan Choker Necklace",
        sku: "SKU-544",
        category: "Jewellery",
        price: 3500,
        quantity: 1,
        historicalCategoryReturnRate: 0.28,
      },
    ],
  },
  {
    id: "ORD-9418",
    customer: mockCustomers[3], // Vikram Malhotra
    cartValue: 4999,
    currency: "₹",
    riskScore: 14,
    confidence: 98,
    policy: "STANDARD_RETURN",
    status: "processed",
    createdAt: "2026-08-26 12:45:18",
    itemsCount: 1,
    riskLevel: "low",
    items: [
      {
        id: "item_8",
        name: "Italian Leather Formal Loafers",
        sku: "SKU-881",
        category: "Footwear",
        size: "UK 9",
        price: 4999,
        quantity: 1,
        historicalCategoryReturnRate: 0.11,
      },
    ],
  },
  {
    id: "ORD-9417",
    customer: mockCustomers[4], // Sneha Patel
    cartValue: 5600,
    currency: "₹",
    riskScore: 62,
    confidence: 88,
    policy: "EXCHANGE_FIRST",
    status: "under_review",
    createdAt: "2026-08-26 12:10:30",
    itemsCount: 3,
    riskLevel: "medium",
    items: [
      {
        id: "item_9",
        name: "Floral Wrap Midi Dress - S",
        sku: "SKU-104-S",
        category: "Womenswear",
        size: "S",
        price: 2800,
        quantity: 1,
        historicalCategoryReturnRate: 0.25,
      },
      {
        id: "item_10",
        name: "Floral Wrap Midi Dress - M",
        sku: "SKU-104-M",
        category: "Womenswear",
        size: "M",
        price: 2800,
        quantity: 1,
        historicalCategoryReturnRate: 0.25,
      },
    ],
  },
  {
    id: "ORD-9416",
    customer: mockCustomers[5], // Aditya Roy
    cartValue: 3150,
    currency: "₹",
    riskScore: 28,
    confidence: 92,
    policy: "STANDARD_RETURN",
    status: "delivered",
    createdAt: "2026-08-26 11:34:55",
    itemsCount: 2,
    riskLevel: "low",
    items: [
      {
        id: "item_11",
        name: "Merino Wool Blend Cardigan",
        sku: "SKU-602",
        category: "Knitwear",
        price: 3150,
        quantity: 1,
        historicalCategoryReturnRate: 0.16,
      },
    ],
  },
  {
    id: "ORD-9415",
    customer: mockCustomers[6], // Meera Nambiar
    cartValue: 14800,
    currency: "₹",
    riskScore: 89,
    confidence: 93,
    policy: "STORE_CREDIT",
    status: "flagged",
    createdAt: "2026-08-26 10:50:12",
    itemsCount: 5,
    riskLevel: "high",
    items: [
      {
        id: "item_12",
        name: "Embellished Velvet Evening Jacket",
        sku: "SKU-311",
        category: "Partywear",
        price: 7400,
        quantity: 1,
        historicalCategoryReturnRate: 0.44,
      },
      {
        id: "item_13",
        name: "Satin Pleated Maxi Skirt",
        sku: "SKU-319",
        category: "Partywear",
        price: 4200,
        quantity: 1,
        historicalCategoryReturnRate: 0.32,
      },
      {
        id: "item_14",
        name: "Crystal Clasp Satin Clutch",
        sku: "SKU-512",
        category: "Accessories",
        price: 3200,
        quantity: 1,
        historicalCategoryReturnRate: 0.18,
      },
    ],
  },
  {
    id: "ORD-9414",
    customer: mockCustomers[7], // Karan Johar
    cartValue: 1899,
    currency: "₹",
    riskScore: 16,
    confidence: 95,
    policy: "STANDARD_RETURN",
    status: "delivered",
    createdAt: "2026-08-26 10:15:00",
    itemsCount: 2,
    riskLevel: "low",
  },
  {
    id: "ORD-9413",
    customer: mockCustomers[8], // Divya Sengupta
    cartValue: 6200,
    currency: "₹",
    riskScore: 58,
    confidence: 87,
    policy: "EXCHANGE_FIRST",
    status: "processed",
    createdAt: "2026-08-26 09:40:22",
    itemsCount: 3,
    riskLevel: "medium",
  },
  {
    id: "ORD-9412",
    customer: mockCustomers[9], // Rohan Kapoor
    cartValue: 3990,
    currency: "₹",
    riskScore: 22,
    confidence: 94,
    policy: "STANDARD_RETURN",
    status: "delivered",
    createdAt: "2026-08-26 09:12:15",
    itemsCount: 1,
    riskLevel: "low",
  },
  {
    id: "ORD-9411",
    customer: mockCustomers[10], // Tanya Chawla
    cartValue: 9800,
    currency: "₹",
    riskScore: 86,
    confidence: 90,
    policy: "STORE_CREDIT",
    status: "flagged",
    createdAt: "2026-08-26 08:35:40",
    itemsCount: 3,
    riskLevel: "high",
  },
  {
    id: "ORD-9410",
    customer: mockCustomers[11], // Manish Reddy
    cartValue: 1550,
    currency: "₹",
    riskScore: 11,
    confidence: 97,
    policy: "STANDARD_RETURN",
    status: "delivered",
    createdAt: "2026-08-26 08:02:11",
    itemsCount: 1,
    riskLevel: "low",
  },
  {
    id: "ORD-9409",
    customer: mockCustomers[0], // Priya Sharma
    cartValue: 4200,
    currency: "₹",
    riskScore: 74,
    confidence: 89,
    policy: "EXCHANGE_FIRST",
    status: "delivered",
    createdAt: "2026-08-25 19:45:00",
    itemsCount: 2,
    riskLevel: "medium",
  },
  {
    id: "ORD-9408",
    customer: mockCustomers[2], // Ananya Iyer
    cartValue: 18500,
    currency: "₹",
    riskScore: 95,
    confidence: 96,
    policy: "RESTOCKING_FEE",
    status: "delivered",
    createdAt: "2026-08-25 16:10:30",
    itemsCount: 5,
    riskLevel: "high",
  },
  {
    id: "ORD-9407",
    customer: mockCustomers[3], // Vikram Malhotra
    cartValue: 8400,
    currency: "₹",
    riskScore: 15,
    confidence: 97,
    policy: "STANDARD_RETURN",
    status: "delivered",
    createdAt: "2026-08-25 14:05:12",
    itemsCount: 2,
    riskLevel: "low",
  },
];
