import { RiskAssessment } from "../types";

export const mockRiskAssessments: Record<string, RiskAssessment> = {
  "ORD-9421": {
    orderId: "ORD-9421",
    riskScore: 81,
    riskLevel: "high",
    confidence: 91,
    evaluatedAt: "2026-08-26 14:18:22",
    signals: {
      customer: [
        {
          id: "sig_c1",
          name: "High Return Ratio",
          description: "Customer has returned 9 of last 14 orders (64.3% return rate vs store average 14.8%).",
          severity: "high",
          value: "64.3% return rate",
          category: "customer",
        },
        {
          id: "sig_c2",
          name: "Short Retention Cycles",
          description: "Average days before return request initiated: 2.1 days from delivery.",
          severity: "medium",
          value: "2.1d avg turnaround",
          category: "customer",
        },
        {
          id: "sig_c3",
          name: "Recent Wardrobing Tag",
          description: "Flagged on previous order ORD-9102 for tags re-attached claims.",
          severity: "high",
          value: "Past incident recorded",
          category: "customer",
        },
      ],
      cart: [
        {
          id: "sig_k1",
          name: "Duplicate SKU Size Bracketing",
          description: "Cart contains size 'M' and size 'L' of the same Embroidered Georgette Anarkali SKU.",
          severity: "high",
          value: "2 sizes (M, L) of same item",
          category: "cart",
        },
        {
          id: "sig_k2",
          name: "High Cart Value Anomaly",
          description: "Cart total ₹7,850 is 1.8x higher than customer's historical average order value.",
          severity: "medium",
          value: "1.8x avg ticket size",
          category: "cart",
        },
        {
          id: "sig_k3",
          name: "Single-Event Accessory Pairing",
          description: "Items match complete weekend occasionwear profile with single accessories.",
          severity: "low",
          value: "Occasion bundle",
          category: "cart",
        },
      ],
      product: [
        {
          id: "sig_p1",
          name: "High Category Return Vulnerability",
          description: "Ethnic Occasionwear category has 38.2% historical return rate across merchant catalog.",
          severity: "high",
          value: "38.2% category return rate",
          category: "product",
        },
        {
          id: "sig_p2",
          name: "Fabric Fragility & Inspection Cost",
          description: "Georgette embroidery requires dedicated manual dry-cleaning and restock inspection.",
          severity: "medium",
          value: "₹450 processing cost/return",
          category: "product",
        },
      ],
    },
    mlPrediction: {
      modelName: "XGBoost Return-Risk Classifier",
      modelVersion: "v2.4.1-prod",
      rawScore: 0.814,
      confidenceScore: 0.912,
      predictedCategory: "Wardrobing Risk",
      features: [
        {
          feature: "size_bracket_count",
          importance: 0.34,
          impact: "positive",
          description: "Multiple sizes for same style detected in cart",
        },
        {
          feature: "customer_historical_return_rate",
          importance: 0.28,
          impact: "positive",
          description: "Historical return frequency is 4.3x baseline",
        },
        {
          feature: "category_fragility_index",
          importance: 0.19,
          impact: "positive",
          description: "High margin, seasonal occasionwear risk profile",
        },
        {
          feature: "account_tenure_days",
          importance: 0.11,
          impact: "negative",
          description: "Account older than 120 days softens fraud likelihood slightly",
        },
        {
          feature: "payment_method_trust",
          importance: 0.08,
          impact: "negative",
          description: "Prepaid UPI transaction reduces non-payment risk",
        },
      ],
    },
  },
  "ORD-9419": {
    orderId: "ORD-9419",
    riskScore: 92,
    riskLevel: "high",
    confidence: 94,
    evaluatedAt: "2026-08-26 13:22:04",
    signals: {
      customer: [
        {
          id: "sig_c4",
          name: "Extreme Serial Return Rate",
          description: "Customer returned 15 of 17 lifetime purchases (88.2% return rate).",
          severity: "high",
          value: "88.2% lifetime returns",
          category: "customer",
        },
        {
          id: "sig_c5",
          name: "High Value Claims",
          description: "3 previous returns claimed damaged on arrival with disputed return inspections.",
          severity: "high",
          value: "3 damage disputes",
          category: "customer",
        },
      ],
      cart: [
        {
          id: "sig_k4",
          name: "High Value Bridal Order",
          description: "Order value ₹12,400 with immediate weekend delivery selection.",
          severity: "high",
          value: "₹12,400 cart total",
          category: "cart",
        },
      ],
      product: [
        {
          id: "sig_p3",
          name: "Bridal Category Volatility",
          description: "Designer bridal wear has a 52% post-event return rate.",
          severity: "high",
          value: "52% return probability",
          category: "product",
        },
      ],
    },
    mlPrediction: {
      modelName: "XGBoost Return-Risk Classifier",
      modelVersion: "v2.4.1-prod",
      rawScore: 0.923,
      confidenceScore: 0.941,
      predictedCategory: "Serial Returner",
      features: [
        {
          feature: "customer_historical_return_rate",
          importance: 0.44,
          impact: "positive",
          description: "Return rate > 85% is top predictor for margin loss",
        },
        {
          feature: "cart_value_to_ltv_ratio",
          importance: 0.29,
          impact: "positive",
          description: "Cart represents high concentration of value",
        },
        {
          feature: "category_fragility_index",
          importance: 0.18,
          impact: "positive",
          description: "Silk lehenga dry clean and refurbish penalty",
        },
        {
          feature: "address_change_frequency",
          importance: 0.09,
          impact: "positive",
          description: "Frequent delivery address alterations",
        },
      ],
    },
  },
  "ORD-9420": {
    orderId: "ORD-9420",
    riskScore: 18,
    riskLevel: "low",
    confidence: 96,
    evaluatedAt: "2026-08-26 13:54:10",
    signals: {
      customer: [
        {
          id: "sig_c6",
          name: "Low Return History",
          description: "Customer has only 1 return across 8 orders (12.5% return rate).",
          severity: "low",
          value: "12.5% return rate",
          category: "customer",
        },
        {
          id: "sig_c7",
          name: "Consistent Size History",
          description: "All past orders are Size 40 with 0 sizing-related exchange requests.",
          severity: "low",
          value: "Consistent sizing",
          category: "customer",
        },
      ],
      cart: [
        {
          id: "sig_k5",
          name: "Standard Workwear Staples",
          description: "Single items of standard cotton essentials matching regular purchase cadence.",
          severity: "low",
          value: "2 distinct items",
          category: "cart",
        },
      ],
      product: [
        {
          id: "sig_p4",
          name: "Low Risk Category",
          description: "Menswear Basics historical return rate is 12.1%, well below threshold.",
          severity: "low",
          value: "12.1% category return rate",
          category: "product",
        },
      ],
    },
    mlPrediction: {
      modelName: "XGBoost Return-Risk Classifier",
      modelVersion: "v2.4.1-prod",
      rawScore: 0.182,
      confidenceScore: 0.964,
      predictedCategory: "Standard Shopper",
      features: [
        {
          feature: "customer_historical_return_rate",
          importance: 0.42,
          impact: "negative",
          description: "Low historical return rate indicates genuine intent",
        },
        {
          feature: "size_consistency_score",
          importance: 0.28,
          impact: "negative",
          description: "Consistent sizing profile across past 300 days",
        },
        {
          feature: "order_ticket_stability",
          importance: 0.20,
          impact: "negative",
          description: "Cart value closely matches average checkout value",
        },
        {
          feature: "sku_repeat_frequency",
          importance: 0.10,
          impact: "negative",
          description: "Repeat customer buying known staple products",
        },
      ],
    },
  },
};
