from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict


class OrderItemDetailSchema(BaseModel):
    product_id: int = Field(..., description="ID of the purchased product")
    product_name: Optional[str] = Field(None, description="Catalog name of the product")
    sku: Optional[str] = Field(None, description="Catalog SKU of the product")
    size: Optional[str] = Field(None, description="Selected size variant (e.g. S, M, L)")
    quantity: int = Field(..., description="Quantity purchased")
    unit_price: float = Field(..., description="Unit price per item")
    total_price: float = Field(..., description="Total line item cost (quantity * unit_price)")

    model_config = ConfigDict(from_attributes=True)


class OrderListItemSchema(BaseModel):
    order_id: int = Field(..., description="Unique order identifier")
    customer_name: str = Field(..., description="Customer full name")
    cart_value: float = Field(..., description="Total monetary value of the order")
    risk_score: Optional[float] = Field(None, description="Predicted risk score (0-100)")
    risk_level: Optional[str] = Field(None, description="Assigned risk tier (LOW, MEDIUM, HIGH)")
    confidence: Optional[float] = Field(None, description="Model prediction confidence score")
    policy: Optional[str] = Field(None, description="Final return policy type applied")
    status: str = Field(..., description="Order processing status (e.g. pending, completed)")
    created_at: datetime = Field(..., description="Order placement timestamp")

    model_config = ConfigDict(from_attributes=True)


class OrderDetailSchema(BaseModel):
    order_id: int = Field(..., description="Unique order identifier")
    customer_id: int = Field(..., description="Customer ID")
    customer_name: str = Field(..., description="Customer full name")
    cart_value: float = Field(..., description="Total monetary value of the order")
    risk_score: Optional[float] = Field(None, description="Predicted risk score (0-100)")
    risk_level: Optional[str] = Field(None, description="Assigned risk tier (LOW, MEDIUM, HIGH)")
    confidence: Optional[float] = Field(None, description="Model prediction confidence score")
    policy: Optional[str] = Field(None, description="Final return policy type applied")
    status: str = Field(..., description="Order processing status")
    created_at: datetime = Field(..., description="Order placement timestamp")
    items: List[OrderItemDetailSchema] = Field(default_factory=list, description="List of items in the order")
    trace_data: Optional[Dict[str, Any]] = Field(None, description="Persisted Agent Decision Trace")
    top_risk_factors: Optional[List[str]] = Field(None, description="Top SHAP risk factors")
    audit_explanation: Optional[str] = Field(None, description="Plain-English audit explanation generated by LLM")
    audit_generated_at: Optional[datetime] = Field(None, description="Timestamp when audit explanation was generated")

    model_config = ConfigDict(from_attributes=True)
